name: Build and Deploy WASM Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Install dependencies
      run: go mod download
      
    - name: Build WASM
      run: |
        GOOS=js GOARCH=wasm go build -o main.wasm main.go
        # wasm_exec.jsを正しい場所からダウンロード
        echo "Downloading wasm_exec.js from correct location..."
        curl -L -o wasm_exec.js https://raw.githubusercontent.com/golang/go/master/lib/wasm/wasm_exec.js
        # ファイルサイズを確認
        ls -la main.wasm wasm_exec.js
        echo "WASM build completed successfully"
        
    - name: Create dist directory
      run: |
        mkdir -p dist
        cp index.html main.wasm wasm_exec.js dist/
        
    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4 